GET http://localhost:666/api/get/637c93b319cfb8713243d0ab
Content-Type: application/json

POST http://localhost:666/api/add-to-group
Content-Type: application/json
{
    // "groupId":"6387fcaf0f32feabcb1f438f",
    "name": "group", 
    "device": {
        // "name": "group1",
        "files": [
            "test-file2.pdf"
            
        ]
    }
}
DELETE http://localhost:666/api/delete-from-group
Content-Type: application/json
{
    "name":"group", 
    "deviceId": "6387fd780b60a2f612e23e4f"
    }
