GET http://localhost:666/api/get/637b64242ee4e39bdea5fb86
Content-Type: application/json

POST http://localhost:666/api/add-to-group
Content-Type: application/json
{
    "groupId":"637b779889f050dd70d2d35c", 
    "device": {
        // "name": "group1",
        "files": [
            "test-file.pdf",
            "test-file.pdf2"
        ]
    }
}