GET http://localhost:666/api/get/637b779889f053dd70d2d35c
Content-Type: application/json

POST http://localhost:666/api/add-to-group
Content-Type: application/json
{
    "groupId":"637c93b319cfb8713243d0ab", 
    "device": {
        // "name": "group1",
        "files": [
            "test-file2.pdf"
            
        ]
    }
}
DELETE http://localhost:666/api/delete-from-group
Content-Type: application/json
{
    "groupId":"637c93b319cfb8713243d0ab", 
    "deviceId": "637b779889f053dd70d2d359"
    }
